apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresomar14
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
        - image: postgres:14-alpine
          name: postgresomar14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: sasa
            - name: POSTGRES_DATABASE
              value: postgres