version: "3.8"
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    build:
      context: ./
      dockerfile: ./msvc-usuarios/Dockerfile
    image: usuarios:latest
#    image: calderonomar48/usuarios-globant  # trae la imagen del dockerhub
    ports:
      - "8001:8001"
#    env_file:
#      - ./msvc-usuarios/.env
    environment:
      PORT: 8001
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: sasa
      CURSOS_URL: ec2-18-207-196-42.compute-1.amazonaws.com
      CURSOS_PORT: 9002
    networks:
      - spring
    depends_on:
      - mysql-db
    restart: always

volumes:
  data-mysql:
    name: data-mysql
networks:
  spring:
    name: spring