#FROM openjdk:17.0.2
#FROM openjdk:20-slim-buster
FROM openjdk:17-alpine

WORKDIR /app/msvc-usuarios

COPY ./pom.xml /app
COPY ./msvc-usuarios .
#COPY ./target/msvc-usuarios-0.0.1-SNAPSHOT.jar /app

# permisos para ejecutar clean package en docker
RUN chmod +x mvnw

#RUN es un comando que se ejecuta cuando se construye la imagen
# aqui esta ejecutando un empaquetado .jar
RUN ./mvnw clean package -DskipTests

EXPOSE 8001

# se va a ejecutar en algun punto de entra y ejecutammos comandos java apuntando al jar
#ENTRYPOINT ["java", "-jar", "msvc-usuarios-0.0.1-SNAPSHOT.jar"]
ENTRYPOINT ["java", "-jar", "./target/msvc-usuarios-0.0.1-SNAPSHOT.jar"]